### ISSUE TITLE
DMPTool homepage content

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmp#3]
TBD pending content inventory
Ideas to add DMPTool blog feed: https://blog.dmptool.org/
or UC stock photo

Wireframe: https://h90c3m.axshare.com/#g=1&p=home

**Comment by rhu001** [comment]
Release round 1 images selected. Craig and I will work on re-sizing versions to address the different responsive break points and have them in folder by 1/24 or 1/25. (https://drive.google.com/drive/folders/1nU_GBGJVNtLjR60usEUcdPNa6fCKryj8) 

We want the following breakpoints and max sizes for homepage images. (These will be revisited and confirmed when Craig and I have finished working on the image resizes.)

1. Small device max and break point (480 px width)
2. Medium device max and break point (765 px width)
3. Large device max and break point (1140 px width)

For best homepage image loading and positioning, please load by CSS as background image instead of using image tag in HTML. Also, please position the background css style so that it is expanding from the "top" position and that the background size style is "cover."

Let me know if you have any questions.

**Comment by rhu001** [comment]
@briri Here are the homepage images for the initial release resized to match the above break points. (https://drive.google.com/drive/folders/1AuzR0nltsPP-g96OBcVrfaDJdJyFWKai?usp=sharing) Let's put them in and see how they perform in real time.

**Comment by rhu001** [comment]
@briri @stephaniesimms Edited homepage wireframe with Usage Metrics put in.
https://h90c3m.axshare.com/#g=1&p=home
Let me know if the above link doesn't work.

**Comment by stephaniesimms** [comment]
the link works @rhu001 - and i'm happy with all the homepage content now but it feels busy. we can talk about streamlining/decluttering approaches on Mon. @briri and i noticed that the large size for the homepage images (3 above) is really large (i.e. too tall maybe?). we can ping you to take a look when the dev server is up and running.

**Comment by stephaniesimms** [comment]
large image size isn't displaying properly on large monitors - I can only see the top half of each image and have to shrink the screen to ca. tablet width to view the whole image. no image displays on mobile.

**Comment by briri** [comment]
@rhu001 I'm not sure if it would be helpful or not, but here is what I have for the CSS rules for the homepage images. Maybe running them by Joel would be a good idea. I'm probably missing something.
```css
/* HOMEPAGE IMAGES */
/* --------------------------------------- */
@media (min-width: 1140px){
  .homepage-img-1 { background-image: url('../images/homepage/1-large.jpg'); }
  .homepage-img-2 { background-image: url('../images/homepage/2-large.jpg'); }
  .homepage-img-3 { background-image: url('../images/homepage/3-large.jpg'); }
  .homepage-img-4 { background-image: url('../images/homepage/4-large.jpg'); }
  .homepage-img-5 { background-image: url('../images/homepage/5-large.jpg'); }
  .homepage-img { height: 493px; }
}
@media (min-width: 765px) and (max-width: 1139px){
  .homepage-img-1 { background-image: url('../images/homepage/1-med.jpg'); }
  .homepage-img-2 { background-image: url('../images/homepage/2-med.jpg'); }
  .homepage-img-3 { background-image: url('../images/homepage/3-med.jpg'); }
  .homepage-img-4 { background-image: url('../images/homepage/4-med.jpg'); }
  .homepage-img-5 { background-image: url('../images/homepage/5-med.jpg'); }
  .homepage-img { height: 393px; }
}
@media (min-width: 480px) and (max-width: 164px){
  .homepage-img-1 { background-image: url('../images/homepage/1-small.jpg'); }
  .homepage-img-2 { background-image: url('../images/homepage/2-small.jpg'); }
  .homepage-img-3 { background-image: url('../images/homepage/3-small.jpg'); }
  .homepage-img-4 { background-image: url('../images/homepage/4-small.jpg'); }
  .homepage-img-5 { background-image: url('../images/homepage/5-small.jpg'); }
  .homepage-img { height: 247px; }
}

.homepage-img {
  position: relative;
  background-color: $white;
  background-position: top;
  background-size: cover;
  background-repeat: no-repeat;
}
```
